#!/usr/bin/env bash
#
# Render the homebrew formula for a released version.
#
#   usage: .github/render-formula.sh <version> <asset-dir>
#
# <asset-dir> holds the release's unix tarballs under the names release.yml
# uploads them. Hashing the *published* assets rather than the local build
# output is deliberate: brew downloads the published bytes, so checksumming
# them is also a check that the upload arrived intact.
#
# Kept as a script rather than inlined in release.yml so the same code that
# runs in CI can seed and re-render the formula by hand.
set -euo pipefail

version="${1:?usage: render-formula.sh <version> <asset-dir>}"
assets="${2:?usage: render-formula.sh <version> <asset-dir>}"

repo="https://github.com/chrisdickinson/ha-ha"

url() {
  echo "$repo/releases/download/v$version/ha-ha-$1.tar.gz"
}

sha() {
  local file="$assets/ha-ha-$1.tar.gz"
  [ -f "$file" ] || { echo "render-formula: missing $file" >&2; exit 1; }
  # shasum is what macOS ships, sha256sum is what the runners have; both
  # print "<hash>  <path>".
  { shasum -a 256 "$file" 2>/dev/null || sha256sum "$file"; } | cut -d' ' -f1
}

# No `version` stanza: brew scans it out of the `v$version` path segment in
# every url, and `brew audit` flags an explicit one as redundant.
cat <<RUBY
# Generated by ha-ha's release workflow. Edits here are overwritten:
# $repo/blob/main/.github/render-formula.sh
class HaHa < Formula
  desc "Name the interfaces the compiler cannot see as one unit"
  homepage "$repo"
  license "MIT"

  on_macos do
    on_arm do
      url "$(url aarch64-apple-darwin)"
      sha256 "$(sha aarch64-apple-darwin)"
    end

    on_intel do
      url "$(url x86_64-apple-darwin)"
      sha256 "$(sha x86_64-apple-darwin)"
    end
  end

  on_linux do
    on_arm do
      url "$(url aarch64-unknown-linux-gnu)"
      sha256 "$(sha aarch64-unknown-linux-gnu)"
    end

    on_intel do
      url "$(url x86_64-unknown-linux-gnu)"
      sha256 "$(sha x86_64-unknown-linux-gnu)"
    end
  end

  def install
    bin.install "ha-ha"
  end

  # "ha-ha validate" is the only command that needs no language server, so the
  # test exercises the binary end to end -- parse, schema-check, report -- in
  # milliseconds, with nothing else installed.
  test do
    (testpath/"ha-ha.kdl").write <<~KDL
      project "rust" "." {
        boundary "demo" target="src/lib.rs#Thing" {
          rule "small" {
            prompt "Keep it small."
          }
        }
      }
    KDL

    assert_match "1 project, 1 boundary, 1 rule",
                 shell_output("#{bin}/ha-ha validate ha-ha.kdl")
  end
end
RUBY
